CREATE DATABASE ComputerService

USE ComputerService

CREATE TABLE Clients (
ClientId INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL
)

CREATE TABLE Mechanics (
MechanicId INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
[Address] NVARCHAR(255) NOT NULL
)

CREATE TABLE Models (
ModelId INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Jobs (
JobId INT PRIMARY KEY IDENTITY,
ModelId INT NOT NULL,
[Status] NVARCHAR(11) DEFAULT 'Pending' CHECK ([Status] IN ('Pending', 'In Progress', 'Finished')),
ClientId INT NOT NULL,
MechanicId INT,
IssueDate DATE NOT NULL,
FinishDate DATE,
CONSTRAINT FK_Jobs_Models
FOREIGN KEY (ModelId) REFERENCES Models(ModelId),
CONSTRAINT FK_Jobs_Clients
FOREIGN KEY (ClientId) REFERENCES Clients(ClientId),
CONSTRAINT FK_Jobs_Mechanics
FOREIGN KEY (MechanicId) REFERENCES Mechanics(MechanicId)
)

CREATE TABLE Orders (
OrderId INT PRIMARY KEY IDENTITY,
JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
IssueDate DATE,
Delivered BIT DEFAULT 0
)

CREATE TABLE Vendors (
VendorId INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Parts (
PartId INT PRIMARY KEY IDENTITY,
SerialNumber NVARCHAR(50) UNIQUE,
[Description] NVARCHAR(255),
Price DECIMAL(6, 2) NOT NULL CHECK(Price > 0),
VendorId INT NOT NULL,
StockQty INT NOT NULL DEFAULT 0 CHECK(StockQty >= 0),
CONSTRAINT FK_Parts_Vendors
FOREIGN KEY(VendorId) REFERENCES Vendors(VendorId)
)

CREATE TABLE OrderParts (
OrderId INT FOREIGN KEY REFERENCES Orders(OrderId),
PartId INT FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT DEFAULT 1 CHECK(Quantity >= 1),
CONSTRAINT PK_OrderParts PRIMARY KEY(OrderId, PartId)
)

CREATE TABLE PartsNeeded (
JobId INT FOREIGN KEY REFERENCES Jobs(JobId),
PartId INT FOREIGN KEY REFERENCES Parts(PartId),
Quantity INT DEFAULT 1 CHECK(Quantity >= 1),
CONSTRAINT PK_PartsNeeded PRIMARY KEY(JobId, PartId)
)